version: '2.0'
services:
  jenkins_server:
    image: "registry.jala.info/devops/jenkins/jenkins:2.107.3-alpine"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home

  gocd_server:
    image: "registry.jala.info/devops/gocd/gocd-server:v18.5.0"
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - /home/ubuntu/dockerGOCD/godata_server:/godata
      - /home/ubuntu/dockerGOCD/go_server:/home/go

  gocd_agent:
    image: "registry.jala.info/devops/gocd/gocd-agent-alpine-3.7:v18.5.0"
    environment:
      - GO_SERVER_URL=https://gocd_server:8154/go
    volumes:
      - /home/ubuntu/dockerGOCD/godata_agent:/godata
      - /home/ubuntu/dockerGOCD/go_agent:/home/go

  sonarqube_server:
    image: "registry.jala.info/devops/sonarqube:6.7.4-alpine"
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - /home/ubuntu/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /home/ubuntu/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /home/ubuntu/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /home/ubuntu/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
